duplicar = ("     *     \n    * *    \n   *   *   \n  *     *  \n ***   *** \n   *   *   \n   *   *   \n   *****   ")
print("     **     ")
print("    ** **    ")
print("   **   **   ")
print("  **     **  ")
print(" ****   **** ")
print("   **   **   ")
print("   **   **   ")
print("   *******   ")
print(duplicar)
print(duplicar * 2)
